default:
  telemetry:
    service: "@format {this.APP}"
    local: false
    log:
      level: INFO
      encoding: utf-8
      format: "%(asctime)s - %(levelname)s - %(name)s - %(message)s"
    metrics:
      service: "@format {this.APP}"
      endpoint: "/metrics"
  probes:
    host: "0.0.0.0"
    port: 8080
    log_level: info
    liveness:
      timeout: 5
      status_code: 204
      endpoint: "/livez"
    readiness:
      timeout: 5
      endpoint: "/readyz"
  # Application name
  app: pipo.transmuter.spotify
  main_task_name: "main_task"
  player:
    queue:
      broker:
        host:
        vhost:
        port:
        timeout: 240
        graceful_timeout: 480     # TODO check if (mili)seconds
        max_consumers: 10
      service:
        transmuter:
          exchange: providers
          routing_key: provider
          youtube_query:
            routing_key: "@format {this.PLAYER__QUEUE__SERVICE__TRANSMUTER__ROUTING_KEY}.youtube.query"
          spotify:
            queue: spotify
            routing_key: "@format {this.PLAYER__QUEUE__SERVICE__TRANSMUTER__ROUTING_KEY}.spotify.*"
            args:
              x-dead-letter-exchange: "dlx"
              x-dead-letter-routing-key: "dl.spotify"
              x-queue-type: quorum
              x-delivery-limit: 3
              message-ttl: 3600000 # 1 hour
    source:
      spotify:
        playlist:
          limit: 50
          filter: "items.track.name,items.track.artists.name"
        album:
          limit: 50     # max allowed by Spotify API
test:
  dynaconf_merge: true
  log:
    level: DEBUG
  channel: "test-channel"
  voice_channel: "test-vchannel"
  server_id: "TEST"
  player:
    queue:
      remote: false
      max_local_music: 100
